---
title: "A4Q6"
output: html_document
date: "2023-03-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Q6
```{r}
library(ISLR)
# attach(Auto)
```

(a)
```{r}
Auto$mpgmed <- factor(as.numeric(Auto$mpg > median(Auto$mpg)))
```

(b)
```{r}
library(e1071)
set.seed(5)
tune.out = tune(svm, mpgmed ~ . - mpg - name, data = Auto, kernel = "linear", ranges = list(cost = c(0.01, 0.1, 1, 5, 10, 100)))
summary(tune.out)
```

(c)
polynomial kernel
```{r}
tune.out = tune(svm, mpgmed ~ . - mpg - name, data = Auto, kernel = "polynomial", ranges = list(cost = c(0.01, 0.1, 1, 5, 10, 100), degree= c(2,3,4)))
summary(tune.out)
```

radial kernel
```{r}
tune.out = tune(svm, mpgmed ~ . - mpg - name, data = Auto, kernel = "radial", ranges = list(cost = c(0.01, 0.1, 1, 5, 10, 100), gamma = c(0.01, 0.1, 1, 5, 10, 100)))
summary(tune.out)
```

(d)
```{r}
library(magrittr) # pipe support
library(dplyr) # for dataframe operations(such as select, filter...)
library(scales) # comma_format()

set.seed(5)
svm_linear = svm(mpgmed ~ . - mpg - name, data = Auto, kernel = "linear", cost = 1)
svm_poly = svm(mpgmed ~ . - mpg - name, data = Auto, kernel = "polynomial", cost = 10, degree = 3)
svm_radial = svm(mpgmed ~ . - Auto$mpg - name, data = Auto, kernel = "radial", cost = 1, gamma = 1)
# plotpairs = function(fit) {
#     for (variable in names(Auto)[!(names(Auto) %in% c("mpg", "mpgmed", "name", "cylinders"))]) {
#        plot(fit, Auto, as.formula(paste("mpg~", variable, sep = "")))
#    }
# }
# plotpairs(svm_radial)
svm_radial_plot_df <- Auto %>% select(mpgmed, weight, horsepower) %>%
  mutate(support = case_when(row_number() %in% svm_radial$index ~ "Yes", T ~ "No"))

# library(ggplot2)
# ggplot(svm_radial_plot_df, aes(x = horsepower, y = weight, col = mpgmed, shape = support)) +
#   geom_point(size = 2) +
#   scale_color_manual(values = c("red", "blue")) +
#   scale_shape_manual(values = c('Yes' = 16, 'No' = 1)) +
#   scale_y_continuous(labels = comma_format()) +
#   labs(shape = "Support Vector:",
#        col = "Actual mpgmed:")
```

linear kernel
```{r}
# plot(svm_radial, 
#      Auto, 
#      weight ~ horsepower, 
#      slice = list(cylinders = median(Auto$cylinders), 
#                   displacement = median(Auto$displacement),
#                   acceleration = median(Auto$acceleration),
#                   year = median(Auto$year), 
#                   origin = Mode(Auto$origin), 
#                   brand = Mode(Auto$brand)))
```

```{r}
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

grid <- expand.grid(horsepower = seq(min(Auto$horsepower), max(Auto$horsepower), length.out = 200), 
                    weight = seq(min(Auto$weight), max(Auto$weight), length.out = 200), 
                    cylinders = median(Auto$cylinders), 
                    displacement = median(Auto$displacement),
                    acceleration = median(Auto$acceleration),
                    year = median(Auto$year), 
                    origin = Mode(Auto$origin))

grid$class_pred <- predict(svm_radial, grid)

library(ggplot2)
ggplot(grid, aes(x = Auto$horsepower, y = Auto$weight)) + 
  geom_tile(aes(fill = grid$class_pred), alpha = 0.5) + 
  geom_point(data = svm_radial_plot_df, aes(col = Auto$mpgmed, shape = svm_radial_plot_df$support), size = 2) +
  scale_color_manual(values = c("red", "blue")) + 
  scale_shape_manual(values = c('Yes' = 16, 'No' = 1)) + 
  scale_y_continuous(labels = comma_format()) +
  labs(shape = "Support Vector:", 
       fill = "Predicted mpg01:", 
       col = "Actual mpg01:") + 
  guides(fill = guide_legend(order = 1),
         col = guide_legend(order = 2), 
         shape = guide_legend(order = 3))
```

```{r}
for (c in names(Auto)) {
  print(length(Auto$c))
}
```